name: mobile
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter

  #Default - HTTP client
  http: ^1.2.2
  #Default - Router
  go_router: ^14.0.0
  #Default - I18n
  easy_localization: ^3.0.7

  #Default - Get Device Id
  device_info_plus: ^11.2.2

  #Geolocation
  geolocator: ^13.0.2

  #WebSocket
  web_socket_channel: ^3.0.3

  #Local Storage
  shared_preferences: ^2.5.4

  #Map
  flutter_map: ^8.0.0
  latlong2: ^0.9.1

  #Shimmer Loading
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#000000"
  image: assets/logo_center.png
  fullscreen: true
  android_12:
    image: assets/logo_center.png
    color: "#000000"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/translations/
    - assets/game/
    - assets/game/lyon9/
