spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/plop2
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #format_sql: true
        #show_sql: true

